name: build and test

on:
  push:
  pull_request:
    branches: [ develop, main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '3.1.x' # The .NET SDK version to use

jobs:
  build:

    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install .NET dependencies
      working-directory: ./MaterialObligatorio/Obligatorio/MinTurBackend
      run: dotnet restore
      
    - name: Build .NET
      working-directory: ./MaterialObligatorio/Obligatorio/MinTurBackend
      run: dotnet build --configuration Release --no-restore
      
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Setup Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Build Angular
      run: |
        npm install
        npm run build
      working-directory: ./MaterialObligatorio/Obligatorio/MinTurFrontend


  test: 

    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps: 
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      working-directory: ./MaterialObligatorio/Obligatorio/MinTurBackend
      run: dotnet restore
      
    - name: Build
      working-directory: ./MaterialObligatorio/Obligatorio/MinTurBackend
      run: dotnet build --configuration Debug --no-restore

    - name: Test
      working-directory: ./MaterialObligatorio/Obligatorio/MinTurBackend
      run: dotnet test --no-build --verbosity normal -l:trx || true
      
    - name: Test report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests Results
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'

    - name: Upload tests results artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsTestsResults
        path: '**/*.trx'
